#!/bin/bash
# vim: ft=sh

SUBCOMMAND_DESC="Abstraction to handle bulk git commands"
SUBCOMMAND_HELP=$(cat <<EOH
This file is used by the 'vcs' command,
and cannot be called directly
EOH
)

# This is a implementation for the 'vcs' subcommand
# using git

# sweepwip is a utility for status and updates on git
# repositories in batch.

function vcs_status() {
  ${SUBCOMMANDS_DIR}/tools/sweepwip -d ${PROJECTS_DIR} -abl
}

function vcs_update() {
  ${SUBCOMMANDS_DIR}/tools/sweepwip -d ${PROJECTS_DIR} -ku
}

