#!/bin/bash
# vim: ft=sh

SUBCOMMAND_DESC="File that exemplifies the usage of the handle_interface"

# takes a UNIX timestamp and returns formatted
# using macos_date
function date_to_date() {
  date -r ${1}
}
