#!/usr/bin/env bash
# vim: ft=sh

use "maintenance"

SUBCOMMAND_DESC="Subcommand description"
SUBCOMMAND_HELP=$(cat <<EOH

hello                      Greetings from bb8
update                     Updates bb8 CLI

EOH
)

BB8_IMG="${ROOT_DIR}/images/bb8"

#Different actions based on arguments
case ${1} in
  hello)
    in_cyan "Hello $(users). I'm here to make your life easier!\n\n"
    cat "${BB8_IMG}"
  ;;
  update)
    if ! bb8_needs_updating; then
      in_cyan "BB8 is already at the latest version\n"
    else
      log "BB8 needs updating"
      in_yellow "You are about to update BB8, do you want to proceed? (Y/n)\n"
      read -r response

      if [[ $response == "Y" ]]; then
        in_cyan "Updating BB8\n"
        git pull
      else
        in_cyan "Update canceled\n"
      fi
    fi

  ;;
esac

