#!/usr/bin/env bash
# vim: ft=sh

use "maintenance"
use "git"

SUBCOMMAND_DESC="Interacts with the bb8 CLI itself"
SUBCOMMAND_HELP=$(cat <<EOH

hello                      Greetings from bb8
status                     Shows if bb8 needs updating
update                     Updates bb8 CLI

EOH
)

BB8_IMG="${ROOT_DIR}/images/bb8.txt"

case ${1} in
  hello)
    in_cyan "Hello $(users). I'm here to help you interact with the QAOps channel!\n\n"
    cat "${BB8_IMG}"
  ;;
  update)
    if bb8_needs_updating; then
      update_bb8
    else
      in_cyan "bb8 is already at the latest version\n"
    fi
  ;;
  status)
    if bb8_needs_updating; then
      in_yellow "bb8 is out of date\nThe current code is from $(last_commit_timestamp)"
    else
      in_cyan "bb8 is already at the latest version\n"
    fi
  ;;
esac


