#!/usr/bin/env bash
# vim: ft=sh
SUBCOMMAND_DESC="Interacts with the bb8 CLI"
SUBCOMMAND_HELP=$(cat <<EOH

hello                      Greetings from bb8
update                     Updates bb8 CLI
new-cmd <CMD>              Create a new subcommand in the bb8 cli
                            - CMD -> name of the new command

EOH
)

NEW_COMMAND_TEMPLATE="${RESOURCES_DIR}/new_command_template"

function bb8_needs_updating() {
  in_cyan "Checking if bb8 has any new changes"

  cd "${ROOT_DIR}"
  git checkout main
  git remote update &> /dev/null
  [[ $(git status | grep -c "Your branch is up to date") -eq 0 ]]
}

function update_bb8() {
  in_yellow "You are about to update bb8 CLI, do you want to proceed? (y/n)"
  read -r response

  if [[ "${response}" == "y" ]]; then
    in_cyan "Updating bb8 CLI"

    cd "${ROOT_DIR}"
    git checkout main
    git pull
  else
    in_cyan "Update cancelled"
  fi
}

#Different actions based on arguments
case ${1} in
  hello)
    in_cyan "Hello $(users). I'm here to make your life easier!!\n\n"
    cat "${BB8_IMG}"
  ;;
  update)
    if bb8_needs_updating; then
      update_bb8
    else
      in_cyan "bb8 is already at the latest version"
    fi
  ;;
  new-cmd)
    cmd="${2}"

    if [[ -z "${cmd}" ]]; then
      in_yellow "You need to specify the name of the new command"
      exit 0
    fi

    in_cyan "Creating a new command called ${cmd}"
    if cp -i "${NEW_COMMAND_TEMPLATE}" "${SUBCOMMANDS_DIR}/${cmd}"; then
      in_green "Command '${cmd}' created. You now can execute '${MAIN_COMMAND} ${cmd}'"
    fi
  ;;
esac

