#!/usr/bin/env bash

DOCS_FOLDER="${PROJECTS_DIR}/docs"

function _show_all_topics() {
  topics=$(ls -l "${DOCS_FOLDER}"/*.md | grep -v "README.md" | awk -F '/' '{print $NF}' | awk -F '-' '{print $1}' | uniq)

  in_cyan "\nList of all QaOps topics:"
  printf "%s\n" "TOPICS"
  printf "\n"
  for topic in ${topics}; do
    printf "%s\n" "${topic}"
  done | sort
}

# vim: ft=sh spell
SUBCOMMAND_DESC="QaOps documentation"
SUBCOMMAND_HELP=$(cat <<EOH

search [TOPIC] [LANGUAGE]                    Will search for the contents in the QaOps docs
                                              - TOPIC    -> topic file to be searched
                                              - LANGUAGE -> either 'pt' or 'en'

$(_show_all_topics)

EOH
)


case ${1} in
  *)
    topic="${1}"
    language="${2}"

    cat "${DOCS_FOLDER}/${topic}-${language}.md"
  ;;

esac