#!/usr/bin/env bash
load_conf repos

function _show_all() {
  in_cyan "\nList of all repository:"
  printf "%-20s %s\n" "ALIAS" "URL"
  printf "\n"
  for name in "${!repos[@]}"; do
    printf "%-20s %s\n" "${name}" "${repos[${name}]}"
  done | sort
}

# vim: ft=sh
SUBCOMMAND_DESC="Provides interactions with QAOps projects"
SUBCOMMAND_HELP=$(cat <<EOH

show                      List all repos
open <ALIAS>              Open the repository in the browser
ALIAS                     The same as "open <ALIAS>"

$(_show_all)

EOH
)

#Different actions based on arguments
case ${1} in
  show)
    _show_all
  ;;
  open)
    alias="${2}"
    log "Alias given ${alias}"
    [[ -n "${repos[${alias}]}" ]] && open_file "${repos[${alias}]}" || _show_all
  ;;
  *)
    alias="${1}"
    [[ -z "${alias}" ]] && return

    log "Alias given ${alias}"
    [[ -n "${repos[${alias}]}" ]] && open_file "${repos[${alias}]}" || _show_all
  ;;
esac

