#!/usr/bin/env bash
load_conf list
load_conf user_options
use 'repos'

function _show_all() {
  in_cyan "\nList of all repository:"
  printf "%-20s %s\n" "ALIAS" "URL"
  printf "\n"
  for name in "${!list[@]}"; do
    printf "%-20s %s\n" "${name}" "${list[${name}]}"
  done | sort
}

# vim: ft=sh
SUBCOMMAND_DESC="Provides interactions with QAOps projects"
SUBCOMMAND_HELP=$(cat <<EOH

show                      List all repos
open <ALIAS>              Open the repository in the browser
ALIAS                     The same as "open <ALIAS>"
download <ALIAS>          Will download repo of the choosen ALIAS to the parent folder of this CLI
                            If <ALIAS> not given, all repositories will be downloaded
install [libs | sws]      Install either libraries or software necessary for working with all QaOps projects
                            - libs -> install all libraries
                            - sws -> install all softwares

$(_show_all)

EOH
)

#Different actions based on arguments
case ${1} in
  show)
    _show_all
  ;;
  open)
    alias="${2}"
    log "Alias given ${alias}"
    [[ -n "${list[${alias}]}" ]] && open_file "${list[${alias}]}" || _show_all
  ;;
  download)
    repo="${2}"
    log "Repo given: ${repo}"

    if [[ -n "${repo}" ]]; then
      download_repo "${repo}"
    else
      download_all_repo
    fi
  ;;
  install)
    choice="${2}"
    log "Choice given: ${choice}"

    install_dependencies "${choice}"
  ;;
  install-v2)
    choice="${2}"
    log "Choice given: ${choice}"

    install_dependencies_v2 "${choice}"
  ;;
  *)
    alias="${1}"
    [[ -z "${alias}" ]] && return

    log "Alias given ${alias}"
    [[ -n "${list[${alias}]}" ]] && open_file "${list[${alias}]}" || _show_all
  ;;
esac

