#!/usr/bin/env bash
# vim: ft=sh
SUBCOMMAND_DESC="Helps setup the bb8cli"
SUBCOMMAND_HELP=$(cat <<EOH

check                      Check if the bb8 has been setup
user                       Creates the user configuration file

EOH
)

USER_CONFIG_FILE_TEMPLATE="${RESOURCES_DIR}/user_config_template"

function check_if_installed() {
  local lib=${1}
  local help_msg=${2:-"please install it"}

  log "The value help_msg: ${help_msg}"

  type -a "${lib}" &> /dev/null

  if [[ $? -ne 0 ]]; then
    in_red "${lib} is not installed in this machine \n${help_msg}"
  else
    in_green "${lib} is installed\n"
  fi
}

function check_if_file_exists() {
  local file="${1}"
    local help_msg=${2:-"file is missing."}

    if [[ -e "${file}" ]]; then
      in_green "${file} file exists"
    else
      in_red "${file} file does not exist.\n${help_msg}"
    fi
}

#Different actions based on arguments
case ${1} in
  check)
    session_title "Check if all necessary software has been installed"
    check_if_installed "git"

    session_title "Check if all necessary configuration has been done"
    check_if_file_exists "${USER_CONFIG_FILE}" "Execute the command '${MAIN_COMMAND} ${SUBCOMMAND} user'"
  ;;
  user)
    in_cyan "Creating the user config file in ${CONFIGURATION_DIR}\n"
    if cp -i "${USER_CONFIG_FILE_TEMPLATE}" "${USER_CONFIG_FILE}"; then
      in_green "File ${USER_CONFIG_FILE} created\nFollow the file's instructions"
    fi
  ;;
esac
