#!/usr/bin/env bash
# vim: ft=sh
SUBCOMMAND_DESC="Subcommand description"
SUBCOMMAND_HELP=$(cat <<EOH

action                      Action documentation

EOH
)

#Different actions based on arguments
case ${1} in
  action)
    echo "Hello World!"
  ;;
esac

