#!/bin/bash
# vim: ft=sh
SUBCOMMAND_DESC="Subcommand description"
SUBCOMMAND_HELP=$(cat <<EOH

hello                      Greetings from bb8

EOH
)

#Different actions based on arguments
case ${1} in
  hello)
    in_cyan "Hello World!\n\n"
    cat "${BB8_IMG}"
  ;;
esac

