#!/bin/bash
# vim: ft=sh
SUBCOMMAND_DESC="Subcommand description"
SUBCOMMAND_HELP=$(cat <<EOH

action                      Describe the action

EOH
)

#Different actions based on arguments
case ${1} in
  action)
    in_cyan "Perform some really cool stuff"
  ;;
esac

