#!/usr/bin/env bash
# vim: ft=sh
SUBCOMMAND_DESC="Validate ids on an API for testing"
SUBCOMMAND_HELP=$(cat <<EOH

start-api             Starts docker wiremock
validator [LIST_IDS]  Check which ID is available in the API
                        [LIST_IDS] List of ids. One id per line

EOH
)

HOST="http://localhost:8080"
ENDPOINT="/users/"
VALID_IDS_FILE="/tmp/valid_ids.txt"

function _validate_api_data() {
  local ids_file="${1}"
  log "Ids file: ${ids_file}"

  mapfile -t ids < "${ids_file}"

#  rm "${VALID_IDS_FILE}" #deletes the file
  in_cyan "======================||===================" >> "${VALID_IDS_FILE}"
  date >> "${VALID_IDS_FILE}"

  count=0
  for id in "${ids[@]}"; do
    in_cyan "Checking ID: ${id}"

    url="${HOST}${ENDPOINT}${id}"
    log "URL: ${url}"

    http_response=$(curl -sw "%{http_code}" "${url}" -o /dev/null)
    in_cyan "HTTP Status: ${http_response}"

    if [[ "${http_response}" == 200 ]]; then
      in_green "Valid ID"
      echo "${id}" >> "${VALID_IDS_FILE}"
    else
      in_red "INVALID ID"
    fi

    (( count=count+1 ))
    in_cyan "Processed ${count} out of ${#ids[@]}"
    in_cyan "==================||================="
  done
}

case ${1} in
  start-api)
    in_cyan "Starting Wiremock server"

    docker run --rm \
          -p 8080:8080 \
          --name wiremock \
          -v "${RESOURCES_DIR}"/wiremock:/home/wiremock \
          wiremock/wiremock:2.33.2
  ;;
  validator)
    ids_file=${2}
    log "Ids file: ${ids_file}"
    _validate_api_data "${ids_file}"
  ;;
esac

