#!/usr/bin/env bash
# vim: ft=sh
SUBCOMMAND_DESC="Useful URL list"

load_conf list

function _show_all() {
  in_cyan "Current URL list:\n"
  printf "%-20s %s\n" "ALIAS" "URL"
  for name in "${!list[@]}";do
    printf "%-20s %s\n" ${name} ${list[${name}]}
  done | sort
}

SUBCOMMAND_HELP=$(cat <<EOH

show            Will list all URLs and aliases

open [ALIAS]    Will invoke 'open URL', in OSX this will
                fire up your browser.

ALIAS           Same as "open [ALIAS]" just a shortcut

$(_show_all)

EOH
)

case ${1} in
  show)
    _show_all
  ;;
esac
